'use client'
import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { FileText, Plus, Search, Check, Clock, Archive, Sparkles, X } from 'lucide-react'
import { getDemoData } from '@/lib/demo-data'
import type { Policy } from '@/types'

const FRAMEWORKS = ['All', 'SOC2', 'GDPR', 'ISO27001', 'PCI_DSS']
const CATEGORIES = ['Access Control','Data Protection','Incident Response','Change Management','Vendor Management','Encryption']
const statusConfig: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  APPROVED: { label: 'Approved', color: '#22c55e', icon: <Check size={12}/> },
  UNDER_REVIEW: { label: 'Under Review', color: '#f59e0b', icon: <Clock size={12}/> },
  AI_GENERATED: { label: 'AI Generated', color: '#6366f1', icon: <Sparkles size={12}/> },
  DRAFT: { label: 'Draft', color: '#8a95a8', icon: <FileText size={12}/> },
  ARCHIVED: { label: 'Archived', color: '#4a5568', icon: <Archive size={12}/> },
}

export default function PoliciesPage() {
  const policies = getDemoData('policies') as Policy[]
  const [selected, setSelected] = useState<Policy>(policies[0]!)
  const [framework, setFramework] = useState('All')
  const [search, setSearch] = useState('')
  const [showGenerate, setShowGenerate] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [generatedText, setGeneratedText] = useState('')
  const [genFramework, setGenFramework] = useState('SOC2')
  const [genCategory, setGenCategory] = useState('Access Control')

  const filtered = policies.filter(p =>
    (framework === 'All' || p.framework === framework) &&
    (p.title.toLowerCase().includes(search.toLowerCase()) || p.category.toLowerCase().includes(search.toLowerCase()))
  )

  const startGenerate = async () => {
    setGenerating(true)
    setGeneratedText('')
    const mockPolicy = `# ${genCategory} Policy\n\n## 1. Purpose\nThis policy establishes requirements for ${genCategory.toLowerCase()} within the organization, aligned with ${genFramework} standards.\n\n## 2. Scope\nApplies to all employees, contractors, and systems processing organizational data.\n\n## 3. Policy Statements\n\n### 3.1 Core Requirements\n- All systems must implement ${genCategory.toLowerCase()} controls before production deployment\n- Regular reviews conducted quarterly by the security team\n- Non-compliance escalated to CISO within 24 hours\n\n### 3.2 Responsibilities\n- **Security Team**: Design and enforce controls\n- **Engineering**: Implement technical safeguards\n- **Management**: Resource allocation and oversight\n\n## 4. Procedures\n1. Submit request via ticketing system\n2. Security review within 5 business days\n3. Annual policy review and update cycle\n\n## 5. Compliance\nViolations result in disciplinary action per HR policy HR-001.\n\n## 6. Review Schedule\nAnnual review. Next review: January 2026.\n\n_Generated by AEGIS using AWS Bedrock (Claude 3.5 Sonnet)_`
    for (let i = 0; i < mockPolicy.length; i += 8) {
      await new Promise(r => setTimeout(r, 25))
      setGeneratedText(mockPolicy.slice(0, i + 8))
    }
    setGenerating(false)
  }

  const cfg = statusConfig[selected.status] ?? statusConfig['DRAFT']!

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24 }}>
      <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between' }}>
        <div>
          <h1 style={{ fontSize: 28, fontWeight: 700, letterSpacing: '-0.5px', marginBottom: 4 }}>Policy <span className="text-gradient">Library</span></h1>
          <p style={{ color: 'var(--text-secondary)', fontSize: 14 }}>{policies.length} policies · AI-powered generation with AWS Bedrock</p>
        </div>
        <motion.button whileHover={{ scale: 1.03 }} whileTap={{ scale: 0.97 }}
          onClick={() => setShowGenerate(true)}
          style={{ padding: '11px 20px', background: '#6366f1', color: '#fff', border: 'none', borderRadius: 10, fontSize: 14, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-display)', display: 'flex', alignItems: 'center', gap: 8, boxShadow: '0 0 20px var(--accent-glow)' }}>
          <Sparkles size={16}/> Generate Policy with AI
        </motion.button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 20, minHeight: 600 }}>
        {/* Left Panel */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          <div style={{ position: 'relative' }}>
            <Search size={16} style={{ position: 'absolute', left: 12, top: 12, color: 'var(--text-muted)' }}/>
            <input placeholder="Search policies..." value={search} onChange={e => setSearch(e.target.value)}
              style={{ width: '100%', padding: '11px 14px 11px 36px', background: 'var(--bg-card)', border: '1px solid var(--border-subtle)', borderRadius: 10, color: 'var(--text-primary)', fontSize: 13, fontFamily: 'var(--font-display)', outline: 'none' }}/>
          </div>
          <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
            {FRAMEWORKS.map(fw => (
              <button key={fw} onClick={() => setFramework(fw)}
                style={{ padding: '5px 12px', borderRadius: 20, fontSize: 12, fontWeight: 500, cursor: 'pointer', fontFamily: 'var(--font-display)', border: `1px solid ${framework === fw ? '#6366f1' : 'var(--border-subtle)'}`, background: framework === fw ? 'rgba(99,102,241,0.15)' : 'transparent', color: framework === fw ? '#818cf8' : 'var(--text-muted)' }}>
                {fw}
              </button>
            ))}
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8, overflowY: 'auto', maxHeight: 520 }}>
            {filtered.map(policy => {
              const cfg = statusConfig[policy.status] ?? statusConfig['DRAFT']!
              return (
                <motion.div key={policy.id} whileHover={{ x: 2 }} onClick={() => setSelected(policy)}
                  style={{ padding: '14px 16px', borderRadius: 12, cursor: 'pointer', background: selected.id === policy.id ? 'rgba(99,102,241,0.08)' : 'var(--bg-card)', border: `1px solid ${selected.id === policy.id ? 'rgba(99,102,241,0.3)' : 'var(--border-subtle)'}`, transition: 'all 0.15s' }}>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 }}>
                    <span style={{ fontSize: 12, color: 'var(--text-muted)', fontWeight: 500 }}>{policy.framework}</span>
                    <span style={{ display: 'flex', alignItems: 'center', gap: 4, padding: '2px 8px', borderRadius: 6, fontSize: 11, fontWeight: 600, background: cfg.color + '22', color: cfg.color }}>
                      {cfg.icon} {cfg.label}
                    </span>
                  </div>
                  <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 4 }}>{policy.title}</div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)' }}>v{policy.version} · {policy.category.replace(/_/g,' ')}</div>
                </motion.div>
              )
            })}
          </div>
        </div>

        {/* Right Panel - Policy Viewer */}
        <div style={{ padding: 28, borderRadius: 16, background: 'var(--bg-card)', border: '1px solid var(--border-subtle)', display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', paddingBottom: 16, borderBottom: '1px solid var(--border-subtle)' }}>
            <div>
              <h2 style={{ fontSize: 20, fontWeight: 700, marginBottom: 6 }}>{selected.title}</h2>
              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                {[selected.framework, selected.category, `v${selected.version}`].map(tag => (
                  <span key={tag} style={{ padding: '3px 10px', borderRadius: 6, fontSize: 12, background: 'var(--bg-surface)', color: 'var(--text-secondary)', border: '1px solid var(--border-subtle)' }}>{tag.replace(/_/g,' ')}</span>
                ))}
                {selected.aiGenerated && <span style={{ padding: '3px 10px', borderRadius: 6, fontSize: 12, background: 'rgba(99,102,241,0.1)', color: '#818cf8', border: '1px solid rgba(99,102,241,0.2)', display: 'flex', alignItems: 'center', gap: 4 }}><Sparkles size={10}/> AI Generated</span>}
              </div>
            </div>
            <div style={{ display: 'flex', gap: 8 }}>
              {selected.status !== 'APPROVED' && <button style={{ padding: '8px 16px', background: '#22c55e', color: '#fff', border: 'none', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-display)' }}>Approve</button>}
              <button style={{ padding: '8px 16px', background: 'var(--bg-surface)', border: '1px solid var(--border-default)', color: 'var(--text-secondary)', borderRadius: 8, fontSize: 13, cursor: 'pointer', fontFamily: 'var(--font-display)' }}>Download PDF</button>
            </div>
          </div>
          <div style={{ flex: 1, overflowY: 'auto', fontFamily: 'var(--font-display)', fontSize: 14, lineHeight: 1.7, color: 'var(--text-secondary)', whiteSpace: 'pre-wrap' }}>
            {selected.content.split('\n').map((line, i) => {
              if (line.startsWith('# ')) return <h1 key={i} style={{ fontSize: 22, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 12, marginTop: i > 0 ? 24 : 0 }}>{line.slice(2)}</h1>
              if (line.startsWith('## ')) return <h2 key={i} style={{ fontSize: 16, fontWeight: 700, color: 'var(--text-primary)', marginBottom: 8, marginTop: 20 }}>{line.slice(3)}</h2>
              if (line.startsWith('### ')) return <h3 key={i} style={{ fontSize: 14, fontWeight: 600, color: '#818cf8', marginBottom: 6, marginTop: 14 }}>{line.slice(4)}</h3>
              if (line.startsWith('- ')) return <div key={i} style={{ paddingLeft: 16, marginBottom: 4, display: 'flex', gap: 8 }}><span style={{ color: '#6366f1' }}>•</span><span>{line.slice(2)}</span></div>
              return <p key={i} style={{ marginBottom: line === '' ? 8 : 4 }}>{line}</p>
            })}
          </div>
        </div>
      </div>

      {/* Generate Modal */}
      <AnimatePresence>
        {showGenerate && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
            style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.7)', zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
            <motion.div initial={{ scale: 0.95, y: 20 }} animate={{ scale: 1, y: 0 }} exit={{ scale: 0.95, y: 20 }}
              style={{ width: '100%', maxWidth: 700, maxHeight: '85vh', background: 'var(--bg-card)', borderRadius: 20, border: '1px solid var(--border-default)', display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
              <div style={{ padding: '24px 28px', borderBottom: '1px solid var(--border-subtle)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <div>
                  <div style={{ fontSize: 18, fontWeight: 700, display: 'flex', alignItems: 'center', gap: 10 }}><Sparkles size={20} color="#6366f1"/> Generate Policy with AI</div>
                  <div style={{ color: 'var(--text-secondary)', fontSize: 13, marginTop: 2 }}>Powered by AWS Bedrock · Claude 3.5 Sonnet</div>
                </div>
                <button onClick={() => { setShowGenerate(false); setGeneratedText(''); setGenerating(false); }}
                  style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'var(--text-muted)' }}><X size={20}/></button>
              </div>
              <div style={{ padding: 28, overflowY: 'auto', flex: 1 }}>
                {!generatedText && !generating ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                    <div>
                      <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Framework</label>
                      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                        {['SOC2','ISO27001','GDPR','PCI_DSS','HIPAA'].map(fw => (
                          <button key={fw} onClick={() => setGenFramework(fw)} style={{ padding: '8px 16px', borderRadius: 8, fontSize: 13, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-display)', border: `1px solid ${genFramework===fw ? '#6366f1' : 'var(--border-subtle)'}`, background: genFramework===fw ? 'rgba(99,102,241,0.15)' : 'var(--bg-surface)', color: genFramework===fw ? '#818cf8' : 'var(--text-secondary)' }}>{fw}</button>
                        ))}
                      </div>
                    </div>
                    <div>
                      <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Policy Category</label>
                      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                        {CATEGORIES.map(cat => (
                          <button key={cat} onClick={() => setGenCategory(cat)} style={{ padding: '8px 16px', borderRadius: 8, fontSize: 13, cursor: 'pointer', fontFamily: 'var(--font-display)', border: `1px solid ${genCategory===cat ? '#6366f1' : 'var(--border-subtle)'}`, background: genCategory===cat ? 'rgba(99,102,241,0.15)' : 'var(--bg-surface)', color: genCategory===cat ? '#818cf8' : 'var(--text-secondary)' }}>{cat}</button>
                        ))}
                      </div>
                    </div>
                    <div>
                      <label style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)', display: 'block', marginBottom: 8 }}>Organization Context</label>
                      <textarea defaultValue="Technology company, ~150 employees, AWS-native infrastructure, serving B2B SaaS customers in the EU and US."
                        style={{ width: '100%', minHeight: 80, padding: '12px 14px', background: 'var(--bg-surface)', border: '1px solid var(--border-default)', borderRadius: 10, color: 'var(--text-primary)', fontSize: 14, fontFamily: 'var(--font-display)', outline: 'none', resize: 'vertical' }}/>
                    </div>
                    <motion.button whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }} onClick={startGenerate}
                      style={{ padding: '14px', background: '#6366f1', color: '#fff', border: 'none', borderRadius: 10, fontSize: 15, fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-display)', boxShadow: '0 0 20px var(--accent-glow)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }}>
                      <Sparkles size={18}/> Generate {genFramework} {genCategory} Policy
                    </motion.button>
                  </div>
                ) : (
                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
                      {generating ? (
                        <><motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1, ease: 'linear' }}><Sparkles size={20} color="#6366f1"/></motion.div>
                        <span style={{ fontSize: 15, fontWeight: 600, color: '#818cf8' }}>AEGIS is generating your policy...</span></>
                      ) : (
                        <><CheckCircle2 size={20} color="#22c55e"/>
                        <span style={{ fontSize: 15, fontWeight: 600, color: '#22c55e' }}>Policy generated! Review and save.</span></>
                      )}
                    </div>
                    <div style={{ padding: 20, background: 'var(--bg-surface)', borderRadius: 12, fontFamily: 'var(--font-display)', fontSize: 13, lineHeight: 1.7, color: 'var(--text-secondary)', whiteSpace: 'pre-wrap', minHeight: 300, border: '1px solid var(--border-subtle)' }}>
                      {generatedText}
                      {generating && <span style={{ color: '#6366f1', animation: 'pulse 1s infinite' }}>▌</span>}
                    </div>
                    {!generating && (
                      <div style={{ display: 'flex', gap: 10, marginTop: 16 }}>
                        <button onClick={() => { setGeneratedText(''); setGenerating(false); }} style={{ flex: 1, padding: '12px', background: 'var(--bg-surface)', border: '1px solid var(--border-default)', borderRadius: 10, color: 'var(--text-secondary)', cursor: 'pointer', fontFamily: 'var(--font-display)' }}>Regenerate</button>
                        <button onClick={() => setShowGenerate(false)} style={{ flex: 2, padding: '12px', background: '#22c55e', border: 'none', borderRadius: 10, color: '#fff', fontWeight: 600, cursor: 'pointer', fontFamily: 'var(--font-display)' }}>Save to Library</button>
                      </div>
                    )}
                  </div>
                )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}
